MULTIMEDIA_BUNDLE_NAME = multimedia
MULTIMEDIA_BUNDLE_ORDER = 041
MULTIMEDIA_BUNDLE_VERSION = v$(shell date +%Y%m%d)
MULTIMEDIA_BUNDLE_LICENSE = GPLv2
MULTIMEDIA_BUNDLE_LICENSE_FILES = COPYING

MULTIMEDIA_BUNDLE_PACKAGES = ffmpeg

$(eval $(bundle-package))
